project:
  output-dir: ./pres

format:
  revealjs: 
    theme: [default]
    slide-number: c/t
    html-math-method: katex

    height: 900
    width: 1600
    auto-stretch: false
    touch: true
    fig-align: "center"

    chalkboard: 
      buttons: false
      theme: whiteboard
    
    pointer:
      key: "q"
      color: "green"
      pointerSize: 16
      alwaysVisible: false

    highlight-style: github
    code-line-numbers: false
    callout-appearance: minimal

    center-title-slide: true

bibliography: references.bib