project:
  type: book

book:
  title: "Survey of CPI Production Systems"
  author: "Collin Brown and Steve Martin"
  date: "2/3/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - concepts.qmd
    - systems-teams-analysis.qmd
    - tools-and-technology.qmd
    - system-age-and-updates.qmd
    - number-of-individuals.qmd
    - change-lead-times.qmd
    - alternative-data.qmd
    - challenges.qmd
    - findings-and-next-steps.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    page-layout: full
    grid:
      sidebar-width: 250px
      body-width: 1000px
      margin-width: 250px
      gutter-width: 1.5rem
  pdf:
    documentclass: scrreprt



