project:
  type: book

book:
  title: "Interim Report: Survey of CPI Production Systems"
  author:
    - name: Collin Brown
      email: collin.brown@statcan.gc.ca
      orcid: 0009-0000-7535-6771
      affiliations:
        - Statistics Canada
    - name: Steve Martin
      orcid: 0000-0003-2544-9480
      email: steve.martin@statcan.gc.ca
      affiliations:
        - Statistics Canada
  date: "4/28/2025"
  chapters:
    - index.qmd
    - concepts.qmd
    - systems-teams-analysis.qmd
    - tools-and-technology.qmd
    - system-age-and-updates.qmd
    - number-of-individuals.qmd
    - change-lead-times.qmd
    - alternative-data.qmd
    - challenges.qmd
    - findings-and-next-steps.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    page-layout: full
    grid:
      sidebar-width: 250px
      body-width: 1000px
      margin-width: 250px
      gutter-width: 1.5rem
  pdf:
    documentclass: scrreprt



